# Required metadata
sonar.language=ts
sonar.projectKey=selector-information-portal
sonar.projectName=selector-information-portal

# Comma-separated paths to directories with sources (required)
sonar.sources=./src
sonar.tests=./src
sonar.test.inclusions=**/*.test.tsx

# Comma-separated paths to directories to be excluded
sonar.exclusions=**/node_modules/**, dist/**, coverage/**, scripts/**, src/mocks/**,

# Encoding of the source files
sonar.sourceEncoding=UTF-8

# Coverage
sonar.coverage.exclusions=
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.javascript.jstestdriver.reportsPaths=./coverage/lcov-report
sonar.surefire.reportsPaths=./coverage/lcov-report
sonar.junit.reportsPaths=./coverage/lcov-report
