# ============================================================================
# Common configuration file
#
# This file must not be edited during installation phase
# It must only contains only parameter that are not envionement dependent
# Env dependent parameter must be store in Env specific configuration file
#
# Parameter defined in this file will be used for 2 usages :
#   1. Exported in Shell for script execution
#      Ex : export PROJECT_NAME=pricing
#   2. Used to susbtitute value in 'text' file located with /*_file/**/*
#      Note that variable in file must be framed with '%%'
#      Ex : replace %%PROJECT_NAME%% by 'pricing'
#
#   Note : Variable can reference other variable previously defined
#      Ex : PROJECT_HOME=${BASE_DIR}/${PROJECT_NAME}
#
# ============================================================================

# -------------------------------------------------------------------------------
# Configuration Bloc (mandatorry for every project but S3 store)
# -------------------------------------------------------------------------------

# Name of the project 
PROJECT_NAME=sc-sip-ui

#  Applicative User
USER_NAME=app

#  Home dir of the Project
BASE_DIR=/app

#  Dir where modified configuration file for the installation (aka sc-widget-static-resources.${ENV}.properties) are stored
CONFIGURATION_DIR=${BASE_DIR}/release/conf/

# Home dir of the Project
PROJECT_HOME=${BASE_DIR}/${PROJECT_NAME}

# RC file to start/stop tomcat
RC_DIR=${PROJECT_HOME}/rc/

# Dir which contains project script
BIN_DIR=${PROJECT_HOME}/bin/

# Place where stand configuration files
CONF_DIR=${PROJECT_HOME}/conf

# Dir where to store installation & operating logs
LOG_DIR=${PROJECT_HOME}/logs

# Dir where to store backups
BACKUP_DIR=${BASE_DIR}/backups

# List of Folder patterns not to parse when substituing values (Default values : node_modules,release)
SUBSTITUTION_EXCLUSIONS=

# -------------------------------------------------------------------------------
# Web Site Installation Bloc (uncomment if WebSite must be deployed , delete otherwise )
# -------------------------------------------------------------------------------
#
# Static WebSite Zip (or list of) to be deployed are stored in folder web_zip. Deployment login is
#    if AWS_S3_BUCKET is defined, we deploy web_zip in S3 Bicket (directly, no sub folder)
#      otherwise, if TOMCAT_HOME is defined, we go Tomcat and ZIP_TARGET_BASEPATH=${TOMCAT_HOME}/webapps/
#      otherwise, if NODEJS_HOME is defined, we go NodeJS and ZIP_TARGET_BASEPATH=${NODEJS_HOME}/
#      otherwise, if HTTPD_WEB_DIR is defined, we go Httpd and ZIP_TARGET_BASEPATH=${HTTPD_WEB_DIR}/
#      otherwise, if NGINX_WEB_DIR is defined, we go NginX and ZIP_TARGET_BASEPATH=${NGINX_WEB_DIR}/
#      otherwise, we just don't install it !
# ZIP_TARGET_NAME define can support the follownig set of value : 
#      - ZIP_TARGET_NAME not defined or empty     -> Any Zip file will be extracted in ${ZIP_TARGET_BASEPATH}
#      - ZIP_TARGET_NAME=<my_web_application>     -> Any Zip file will be extracted in ${ZIP_TARGET_BASEPATH}
#      - ZIP_TARGET_NAME=<web_app_1>,<web_app_2>,...,<web_app_N> -> List folder in ${ZIP_TARGET_BASEPATH} for every zip file in web zip buinary bundle (web_zip/), sorted by file name
ZIP_TARGET_NAME=

# -------------------------------------------------------------------------------
# Web Bucket are configured in env related files (at least, they really should !!! )
# On env CI, SQE, PPR, Web Bucket is stored in RDITS accessed interannly in SE only
# On env PROD, Web Bucket is stored in AWS S3 and CloudFront, exposed on the Web
# For other purpose, Demo, Field Test, ... other AWS S3/CF can be provided
# -------------------------------------------------------------------------------

