# ============================================================================
# SQE-Specific Configuration file for Project sc-sip-ui ()
# ============================================================================

# DNS Name of the server (if ${HOSTNAME} is not ok, you can try ${IP})
SERVER_NAME=${HOSTNAME}

# -------------------------------------------------------------------------------
# AWS S3 Configuration Bloc (uncomment if AWS S3 deployment required )
# -------------------------------------------------------------------------------
# AWS S3 Bucket
# AWS_S3_BUCKET=euw-s3-dces-selectconfig-sip-sqe
AWS_S3_BUCKET=euw-s3-dces-scadmin-data-prd
# euw-s3-dces-selectconfig-int
#
# # AWS S3 Region
# #   -> us-east-1 ( US East, N. Virginia), us-west-1 ( US West, N. California), us-west-2 (US West, Oregon), sa-east-1 (South America, S�o Paulo)
# #   -> eu-west-1 (EU, Ireland), eu-central-1 (EU, Frankfurt)
# #   -> ap-northeast-1 (Asia Pacific, Tokyo), ap-northeast-2 (Asia Pacific, Seoul), ap-southeast-1 (Asia Pacific, Singapore), ap-southeast-2 (Asia Pacific, Sydney)
AWS_DEFAULT_REGION=eu-west-1
#
# # #  AWS Access Credentials
AWS_ACCESS_KEY_ID=
AWS_ACCESS_KEY_SECRET=
#
WEBBUCKET_URL=https://s3-${AWS_DEFAULT_REGION}.amazonaws.com/${AWS_S3_BUCKET}/
WEBBUCKET_SYNC_OPTIONS=--delete --cache-control max-age=180
WEBBUCKET_WEB_FOLDERS=sip/

# Applicaiton variables
SIP_CONFIGURE_URL=https://selectconfig-data.schneider-electric.com/usm-admin-services/selectors
SIP_CONSUMPTION_URL=https://selectconfig-data.schneider-electric.com/usm-services/selectors
SIP_ADMINISTRATION_URL=https://gw-api.schneider-electric.com/sc/v2.5/administration/
POST_MESSAGE_TARGET=*
PRODUCTION_MODE=true
WIDGET_URL=https://sc-widget-player.schneider-electric.com/index.html?
SIP_BACKEND_ENV=data
S_AND_C_WEBSITE_URL=https://selectconfig-admin.schneider-electric.com/
